In [1]:
import torch

In [4]:
x = torch.randint(23,78,(6,))
x

tensor([44, 33, 70, 61, 67, 66])

In [6]:
x = torch.tensor([[0.1,1.5],[5.6,7.8],[4.9,7.8]])
x

tensor([[0.1000, 1.5000],
        [5.6000, 7.8000],
        [4.9000, 7.8000]])

In [8]:
zeros = torch.zeros(5,6)
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [10]:
torch.linspace(3 , 10 , steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
torch.logspace(start=20 , end=30 , steps=6)

tensor([1.0000e+20, 1.0000e+22, 1.0000e+24, 1.0000e+26, 1.0000e+28, 1.0000e+30])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [23]:
import time

In [24]:
%%time

start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00000000
CPU times: total: 0 ns
Wall time: 0 ns


In [19]:
import numpy as np

torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.01252341
0.08684754
